app/models.py
#!/usr/bin/env python
# -*-coding:utf-8-*-
from datetime import datetime
from flask import current_app
from werkzeug.security import generate_password_hash, check_password_hash #密码散列
from flask_login import UserMixin, AnonymousUserMixin #认证用户
from . import db, login_manager

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer #确认用户账户

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(64), unique = True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' %self.name

    @staticmethod
    def insert_roles():
        roles = {
            'User': (
                Permission.FOLLOW |
                Permission.COMMENT |
                Permission.WRITE_ARTICLES,
                True
                     ),
            'Moderator': (
                Permission.FOLLOW |
                Permission.COMMENT |
                Permission.WRITE_ARTICLES |
                Permission.MODERATE_COMMENTS,
                False
                     ),
            'Administrator': (
                0xff,
                False
            )
        }
        for r in roles:
            role = Role.query.filter_by(name=r).first()
           # print("role: ", role)
           # print("r: ", r)
            if role is None:
                role = Role(name=r)
                role.permissions = roles[r][0]
                role.default = roles[r][1]
                db.session.add(role)
        db.session.commit()


#Role权限代码
class Permission:
    FOLLOW = 0x01
    COMMENT = 0X02
    WRITE_ARTICLES = 0X04
    MODERATE_COMMENTS = 0X08
    ADMINISTER = 0X80


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(64), unique = True, index = True)
    username = db.Column(db.String(64), unique = True, index = True)
    password_hash = db.Column(db.String(128))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    confirmed = db.Column(db.Boolean, default = False)
    #10.1增加用户资料信息
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    last_seen = db.Column(db.DateTime(), default=datetime.utcnow)

    # #重写is_authenticated方法
    # @property
    # def is_authenticated(self):
    #     return self.confirmed

    #用户最后访问时间
    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)

    #定义默认的用户角色
    def __init__(self, **kwargs):
        super(User,self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(permissions=0xff).first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()

    #检查用户是否有指定的权限,角色验证

    def can(self, permissions):
        return self.role is not None and \
               (self.role.permissions & permissions) == permissions


    def is_administrator(self):
        return self.can(Permission.ADMINISTER)

    def __repr__(self):
        return '<User %r>' %self.username

    @property
    def password(self):
        raise AttributeError('password is note a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


    #生成令牌,有效期为1小时
    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    #检验令牌
    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        return True


#?
class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False


login_manager.anonymous_user = AnonymousUser


# 加载用户的回调函数LoginManager.user_loader
@login_manager.user_loader
def load_user(user_id):
    print("加载用户回调函数load_user from models模块")
    return User.query.get(int(user_id))

app/main/forms.py
#!/usr/bin/env python
# -*-coding:utf-8-*-
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Required


class NameForm(Form):
    name = StringField('what is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
# -*-coding:utf-8-*-
"""程序的工厂函数在app包中的构造文件定义"""

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_moment import Moment
from config import config
from flask_login import LoginManager




bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()

#实例化login_manager
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # ?init_app()函数
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    # 在工厂函数中初始化认证用户
    login_manager.init_app(app)
    #print(login_manager)
    # 附加路由和自定义的错误页面

    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint)
    #print(main_blueprint)

    #将auth认证蓝本注册到create_app函数中
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/auth')

    # 加载用户的回调函数LoginManager.user_loader
    @login_manager.user_loader
    def load_user(user_id):
        print("加载用户回调函数load_user from app.init模块")
        from app.models import User
        return User.query.get(int(user_id))

    return app

app/main/__init__.py
# -*-coding:utf-8-*-

from flask import Blueprint

main = Blueprint('main', __name__)

#导入views,errors模块能把路由和处理错误程序与蓝本关联起来.
#注意,这些模块在脚本末尾导入,是为了笔漫循环导入依赖,因为在views.py和errors.py中还要导入蓝本main
from . import views, errors

#把Permission类加入模板上下文
@main.app_context_processor
def inject_permissions():
    from app.models import Permission
    return dict(Permission=Permission)

app/main/views.py
# -*-coding:utf-8-*-
from flask import render_template, abort, redirect, session, url_for
from datetime import datetime
from . import main
from ..models import User
from forms import NameForm

@main.route('/')
def index():
    #return render_template('index.html')
    form = NameForm()
    if form.validate_on_submit():
        #...
        return redirect(url_for('index'))
    return render_template('index.html',
                           form = form,
                           name = session.get('name'),
                           known = session.get('known', False),
                           current_time = datetime.utcnow())


#用户资料页面路由
@main.route('/user/<username>')
def user(username):
    print(username)
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('user.html', user=user)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>

            {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
            {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
    <h1>{{ user.username }}</h1>
    {% if user.name or user.location %}
    <p>
        {% if user.name %}{{ user.name }}{% endif %}
        {% if user.location %}
            From <a href="http://maps.google.com/?p={{user.location }}">{{ user.location }}</a>
        {% endif %}
    </p>
    {% endif %}
    {% if current_user.is_administrator() %}
    <p><a href="mailto:{{ user.email }}">""{{ user.email }}</a></p>
    {% endif %}
    {% if user.about_me %}
        <p>{{ user.about_me }}</p>
    {% endif %}
    <p>
        Member since {{ moment(user.member_since).format('L') }}.
        Last seen {{ moment(user.last_seen).fromNow() }}
    </p>

</div>
{% endblock %}